### ISSUE TITLE
t/00-compile.t fail on "perl in space"

### ISSUE THREAD

**Issue by mohawk2** [dagolden/IO-Prompt-Tiny#1]
```
#   Failed test 'IO::Prompt::Tiny loaded ok'
#   at t\00-compile.t line 62.
#                   ''
#     doesn't match '(?^s:^\s*IO::Prompt::Tiny ok)'
# Looks like you failed 1 test of 1.
```

Reason: this line:

```
    like( qx{ $^X -Ilib -e "require $_; print '$_ ok'" }, qr/^\s*$_ ok/s, "$_ loaded ok" )
```

needs `""` around `$^X`. Latest Dist::Zilla::Plugin::Test::Compile seems to fix. @karenetheridge says just making new dist with latest T::C will fix. Could you? Then I'll retry on my "perl in space".

**Comment by dagolden** [comment]
Re-released to CPAN without compilation test.
